-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sales_transaction
(
    transaction_id bigserial,
    date date,
    "time" time without time zone,
    sales_outlet integer,
    staff integer,
    customer integer,
    PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id text,
    product text,
    product_type_id integer,
    description text,
    price numeric,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    sales_detail_id bigserial,
    transaction_id bigint NOT NULL,
    product_id text NOT NULL,
    quantity integer,
    price numeric,
    PRIMARY KEY (sales_detail_id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    product_type_id integer,
    category text,
    type text,
    PRIMARY KEY (product_type_id)
);

ALTER TABLE IF EXISTS public.product
    ADD FOREIGN KEY (product_type_id)
    REFERENCES public.product_type (product_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY (transaction_id, product_id)
    REFERENCES public.sales_transaction (transaction_id, product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;